### ISSUE TITLE
Bot goes inactive

### ISSUE THREAD

**Issue by bhageshvar** [destructiondogo/bitmex-copy-bot#4]
After running the bot on the vps for lets say 20 or 30 minutes in the initial period, there are no errors and orders pass flawlessly. 
However, after 20 or 30 minutes even without uninterrupted Internet connection on the vps or personal device, the bot goes inactive, it has not crashed, has not thrown any errors its still running. 

But any new activities on the leader account, does not get copied into the followers account anymore. Have to restart the bot every few minutes to reestablish connection. 
Anyof you faced similar issue? Seeing this in mainnet and testnet.

**Comment by bhageshvar** [comment]
Still facing the same issues. Although on the terminal the program is running without errors, after a few minutes or so, no ordercopying or amending happens on both testnet and mainnet.

**Comment by tolgamorf** [comment]
@bhageshvar I think it is mostly related to high CPU usage.

First of all, take a look at the below line, here we actually only need the `executions` channel from the websocket. Especially the `orderBookL2` channel streams LOTS of data, which is unnecessary.

https://github.com/destructiondogo/bitmex-copy-bot/blob/211331fb8f8d5a5b2ee8965c7f6530045c9facd2/bitmex_websocket.py#L195

Next, in my own code I added a `sleep(0.1)` in the `while` loop in `run.py`.

Finally, as a precaution in my main loop, I added an infinite loop with a `try/catch` which restarts the bot if there is an error. Because sometimes maybe due to a connection issue or something like that, the websocket object becomes `None`, and when that happens, the bot restarts.

**Comment by tolgamorf** [comment]
A note that I forgot to add about CPU usage:

In its current state, the bot uses 100% CPU on my PC, but with the changes that I mentioned above, it is very low now.

**Comment by bhageshvar** [comment]
I see, have you already pushed it to repo ?

**Comment by bhageshvar** [comment]
Actually, I ran this in a vps with nothing else running, but still had this issue. Dogo had merged your previous commit and was using that version here.

**Comment by tolgamorf** [comment]
Well no because my code editor changes all the formatting (due to linter) so it will be an enormous change. Let me try to make it simple and push.

**Comment by tolgamorf** [comment]
> I see, have you already pushed it to repo ?

Well no because my code editor changes all the formatting (due to linter) so it will be an enormous change. Let me try to make it simple and push.

**Comment by bhageshvar** [comment]
Would be great if you can push, I have been breaking my head trying to make this work for many days now and havent figured it out

**Comment by tolgamorf** [comment]
> Would be great if you can push, I have been breaking my head trying to make this work for many days now and havent figured it out

Changes pushed to my fork: https://github.com/tolgamorf/bitmex-copy-bot
Also created a pull request. #5

**Comment by bhageshvar** [comment]
Thanks a lot. I think it all works now. 
@tolgamorf this code does not change leverage for copy accounts though. Have you earlier tried to look into that issue and probably add to the code ? Just curious.

**Comment by tolgamorf** [comment]
Yes, the leverage stays the same, never changes. I didn't write any code for that because I always use cross :)
